name: Create Tag

on:
  push:
    branches:
      - CVAT*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create tag
          uses: actions/github-script@v5
          with:
            script: |
              github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'refs/tags/2.0',
                sha: context.sha
              })