name: Continuous Integration - Automatic Tagging

on:
  push:
    branches:
      - CVAT*

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get version
        id: vars
        run: echo ::set-output name=version::$(cat version.txt)
      - name: Check version
        uses: mukunku/tag-exists-action@v1.0.0
        id: checkTag
        with: 
          tag: 'v1'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create tag
        uses: actions/github-script@v5
        if: ${{ 'steps.checkTag.outputs.exists' }}
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.vars.outputs.version }}',
              sha: context.sha
            })