name: Continuous Integration - Automatic Tagging

on:
  push:
    branches:
      - CVAT*

jobs:
  file_checking:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check version.txt existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "version.txt"

      - run: echo ::set-output name=file_exist::${{ steps.check_files.outputs.files_exists }}
  
  tagging:
    needs: [file_checking]
    if: needs.file-checking.outputs.file_exist == 'true'
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Retrieve version from version.txt
        id: vars
        run: echo ::set-output name=version::$(cat version.txt)

      - name: Check version existence
        uses: mukunku/tag-exists-action@v1.0.0
        id: checkTag
        with:
          tag: ${{ steps.vars.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create version tag
        uses: actions/github-script@v5
        if: ${{ steps.checkTag.outputs.exists == 'false' }}
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.vars.outputs.version }}',
              sha: context.sha
            })